import * as Icon from "phosphor-react";
import { IconEntry, IconCategory } from ".";

export const icons: Readonly<IconEntry[]> = [
  {
    name: "alarm",
    categories: [IconCategory.SYSTEM],
    tags: ["times", "timer", "clock", "schedule", "events", "watch"],
    Icon: Icon.Alarm,
  },
  {
    name: "android",
    categories: [
      IconCategory.BRAND,
      IconCategory.COMMUNICATION,
      IconCategory.DEVELOPMENT,
      IconCategory.DEVICE,
      IconCategory.SYSTEM,
    ],
    tags: ["android", "google", "mobile", "phone", "cellular", "cellphone"],
    Icon: Icon.Android,
  },
  {
    name: "archive",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: [
      "saved",
      "saving",
      "archived",
      "archiving",
      "archival",
      "downloaded",
      "downloading",
    ],
    Icon: Icon.Archive,
  },
  {
    name: "archive-bin",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: [
      "saved",
      "saving",
      "archived",
      "archiving",
      "archival",
      "downloaded",
      "downloading",
    ],
    Icon: Icon.ArchiveBin,
  },
  {
    name: "archive-box",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: [
      "saved",
      "saving",
      "archived",
      "archiving",
      "archival",
      "downloaded",
      "downloading",
    ],
    Icon: Icon.ArchiveBox,
  },
  {
    name: "archive-disk-dot",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: [
      "saved",
      "saving",
      "archived",
      "archiving",
      "archival",
      "downloaded",
      "downloading",
    ],
    Icon: Icon.ArchiveDiskDot,
  },
  {
    name: "archive-disk-line",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: [
      "saved",
      "saving",
      "archived",
      "archiving",
      "archival",
      "downloaded",
      "downloading",
    ],
    Icon: Icon.ArchiveDiskLine,
  },
  {
    name: "archive-simple",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: [
      "saved",
      "saving",
      "archived",
      "archiving",
      "archival",
      "downloaded",
      "downloading",
    ],
    Icon: Icon.ArchiveSimple,
  },
  {
    name: "arrow-bend-down-left",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowBendDownLeft,
  },
  {
    name: "arrow-bend-down-right",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowBendDownRight,
  },
  {
    name: "arrow-bend-left-down",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowBendLeftDown,
  },
  {
    name: "arrow-bend-left-up",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowBendLeftUp,
  },
  {
    name: "arrow-bend-right-down",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowBendRightDown,
  },
  {
    name: "arrow-bend-up-left",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowBendUpLeft,
  },
  {
    name: "arrow-bend-up-right",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowBendUpRight,
  },
  {
    name: "arrow-clockwise",
    categories: [IconCategory.OTHER],
    tags: [
      "directional",
      "pointer",
      "pointing",
      "arrowhead",
      "redo",
      "refreshing",
    ],
    Icon: Icon.ArrowClockwise,
  },
  {
    name: "arrow-counter-clockwise",
    categories: [IconCategory.OTHER],
    tags: [
      "directional",
      "pointer",
      "pointing",
      "arrowhead",
      "undo",
      "refreshing",
    ],
    Icon: Icon.ArrowCounterClockwise,
  },
  {
    name: "arrow-double-left-circle",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowDoubleLeftCircle,
  },
  {
    name: "arrow-double-right-circle",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowDoubleRightCircle,
  },
  {
    name: "arrow-down-circle",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowDownCircle,
  },
  {
    name: "arrow-down-left-circle",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowDownLeftCircle,
  },
  {
    name: "arrow-down-left-elbow",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowDownLeftElbow,
  },
  {
    name: "arrow-down-left-line",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowDownLeftLine,
  },
  {
    name: "arrow-down-line",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowDownLine,
  },
  {
    name: "arrow-down-right-circle",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowDownRightCircle,
  },
  {
    name: "arrow-down-right-elbow",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowDownRightElbow,
  },
  {
    name: "arrow-down-right-line",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowDownRightLine,
  },
  {
    name: "arrow-elbow-left",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowElbowLeft,
  },
  {
    name: "arrow-elbow-right",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowElbowRight,
  },
  {
    name: "arrow-left-circle",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowLeftCircle,
  },
  {
    name: "arrow-left-down-elbow",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowLeftDownElbow,
  },
  {
    name: "arrow-left-line",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowLeftLine,
  },
  {
    name: "arrow-right-circle",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowRightCircle,
  },
  {
    name: "arrow-right-line",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowRightLine,
  },
  {
    name: "arrow-right-up-elbow",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowRightUpElbow,
  },
  {
    name: "arrow-u-down-left",
    categories: [IconCategory.OTHER],
    tags: [
      "directional",
      "pointer",
      "pointing",
      "arrowhead",
      "undo",
      "return",
      "backwards",
      "u-turns",
    ],
    Icon: Icon.ArrowUDownLeft,
  },
  {
    name: "arrow-u-down-right",
    categories: [IconCategory.OTHER],
    tags: [
      "directional",
      "pointer",
      "pointing",
      "arrowhead",
      "redo",
      "forwards",
      "u-turns",
    ],
    Icon: Icon.ArrowUDownRight,
  },
  {
    name: "arrow-u-left-down",
    categories: [IconCategory.OTHER],
    tags: [
      "directional",
      "pointer",
      "pointing",
      "arrowhead",
      "undo",
      "return",
      "backwards",
      "u-turns",
    ],
    Icon: Icon.ArrowULeftDown,
  },
  {
    name: "arrow-u-left-up",
    categories: [IconCategory.OTHER],
    tags: [
      "directional",
      "pointer",
      "pointing",
      "arrowhead",
      "redo",
      "forwards",
      "u-turns",
    ],
    Icon: Icon.ArrowULeftUp,
  },
  {
    name: "arrow-u-right-down",
    categories: [IconCategory.OTHER],
    tags: [
      "directional",
      "pointer",
      "pointing",
      "arrowhead",
      "undo",
      "return",
      "backwards",
      "u-turns",
    ],
    Icon: Icon.ArrowURightDown,
  },
  {
    name: "arrow-u-right-up",
    categories: [IconCategory.OTHER],
    tags: [
      "directional",
      "pointer",
      "pointing",
      "arrowhead",
      "redo",
      "forwards",
      "u-turns",
    ],
    Icon: Icon.ArrowURightUp,
  },
  {
    name: "arrow-u-up-left",
    categories: [IconCategory.OTHER],
    tags: [
      "directional",
      "pointer",
      "pointing",
      "arrowhead",
      "undo",
      "return",
      "backwards",
      "u-turns",
    ],
    Icon: Icon.ArrowUUpLeft,
  },
  {
    name: "arrow-u-up-right",
    categories: [IconCategory.OTHER],
    tags: [
      "directional",
      "pointer",
      "pointing",
      "arrowhead",
      "redo",
      "forwards",
      "u-turns",
    ],
    Icon: Icon.ArrowUUpRight,
  },
  {
    name: "arrow-up-circle",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowUpCircle,
  },
  {
    name: "arrow-up-left-circle",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowUpLeftCircle,
  },
  {
    name: "arrow-up-left-line",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowUpLeftLine,
  },
  {
    name: "arrow-up-line",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowUpLine,
  },
  {
    name: "arrow-up-right-circle",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowUpRightCircle,
  },
  {
    name: "arrow-up-right-line",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowUpRightLine,
  },
  {
    name: "arrows-clockwise",
    categories: [IconCategory.OTHER],
    tags: [
      "directional",
      "pointer",
      "pointing",
      "arrowhead",
      "redo",
      "refreshing",
    ],
    Icon: Icon.ArrowsClockwise,
  },
  // {
  //   name: "arrows-counter-clockwise",
  //   categories: [IconCategory.OTHER],
  //   tags: ["directional", "pointer", "pointing", "arrowhead", "undo", "refreshing"],
  //   Icon: Icon.ArrowsCounterClockwise,
  // },
  {
    name: "arrows-down-up",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowsDownUp,
  },
  {
    name: "arrows-left-right",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.ArrowsLeftRight,
  },
  {
    name: "arrows-outward",
    categories: [IconCategory.OTHER],
    tags: [
      "directional",
      "pointer",
      "pointing",
      "arrowhead",
      "expand",
      "fullscreen",
    ],
    Icon: Icon.ArrowsOutward,
  },
  {
    name: "arrows-outward-cardinal",
    categories: [IconCategory.OTHER],
    tags: [
      "directional",
      "pointer",
      "pointing",
      "arrowhead",
      "expand",
      "fullscreen",
      "pan",
    ],
    Icon: Icon.ArrowsOutwardCardinal,
  },
  {
    name: "asterisk",
    categories: [IconCategory.OTHER],
    tags: ["star", "wildcard", "bullet point", "6"],
    Icon: Icon.Asterisk,
  },
  {
    name: "asterisk-eight",
    categories: [IconCategory.OTHER],
    tags: ["star", "wildcard", "bullet point", "8"],
    Icon: Icon.AsteriskEight,
  },
  {
    name: "at",
    categories: [IconCategory.OTHER],
    tags: ["@", "address", "email", "at symbol", "commercial at", "arobase"],
    Icon: Icon.At,
  },
  {
    name: "backspace",
    categories: [IconCategory.SYSTEM],
    tags: ["keyboard", "remove", "delete"],
    Icon: Icon.Backspace,
  },
  {
    name: "battery-charging",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: ["charged", "charger", "charging", "power"],
    Icon: Icon.BatteryCharging,
  },
  {
    name: "battery-charging-vertical",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: ["charged", "charger", "charging", "power"],
    Icon: Icon.BatteryChargingVertical,
  },
  {
    name: "battery-empty",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: ["charged", "charger", "charging", "power", "dead"],
    Icon: Icon.BatteryEmpty,
  },
  {
    name: "battery-full",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: ["charged", "charger", "charging", "power", "filled"],
    Icon: Icon.BatteryFull,
  },
  {
    name: "battery-full-hatch",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: ["charged", "charger", "charging", "power", "filled"],
    Icon: Icon.BatteryFullHatch,
  },
  {
    name: "battery-high",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: ["charged", "charger", "charging", "power"],
    Icon: Icon.BatteryHigh,
  },
  {
    name: "battery-high-hatch",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: ["charged", "charger", "charging", "power"],
    Icon: Icon.BatteryHighHatch,
  },
  {
    name: "battery-low",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: ["charged", "charger", "charging", "power"],
    Icon: Icon.BatteryLow,
  },
  {
    name: "battery-low-hatch",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: ["charged", "charger", "charging", "power"],
    Icon: Icon.BatteryLowHatch,
  },
  {
    name: "battery-medium",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: ["charged", "charger", "charging", "power"],
    Icon: Icon.BatteryMedium,
  },
  {
    name: "battery-medium-hatch",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: ["charged", "charger", "charging", "power"],
    Icon: Icon.BatteryMediumHatch,
  },
  {
    name: "bell",
    categories: [IconCategory.SYSTEM],
    tags: [
      "alarm",
      "notifications",
      "times",
      "timer",
      "clock",
      "schedule",
      "events",
    ],
    Icon: Icon.Bell,
  },
  {
    name: "bell-simple",
    categories: [IconCategory.SYSTEM],
    tags: [
      "alarm",
      "notifications",
      "times",
      "timer",
      "clock",
      "schedule",
      "events",
    ],
    Icon: Icon.BellSimple,
  },
  {
    name: "bluetooth",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: ["wireless", "connection", "connected", "connectivity"],
    Icon: Icon.Bluetooth,
  },
  {
    name: "bluetooth-connected",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: ["wireless", "connection", "connected", "connectivity"],
    Icon: Icon.BluetoothConnected,
  },
  {
    name: "book",
    categories: [IconCategory.DOCUMENT, IconCategory.OTHER],
    tags: ["reading", "reader", "novel", "story", "library"],
    Icon: Icon.Book,
  },
  {
    name: "book-open",
    categories: [IconCategory.DOCUMENT, IconCategory.OTHER],
    tags: ["reading", "reader", "novel", "story", "library"],
    Icon: Icon.BookOpen,
  },
  // {
  //   name: "book-closed",
  //   categories: [IconCategory.DOCUMENT, IconCategory.OTHER],
  //   tags: ["reading", "reader", "novel", "story"],
  //   Icon: Icon.BookClosed,
  // },
  {
    name: "bookmark",
    categories: [IconCategory.DOCUMENT, IconCategory.OTHER],
    tags: [
      "reading",
      "reader",
      "novel",
      "story",
      "placeholder",
      "favorites",
      "favorited",
      "library",
    ],
    Icon: Icon.Bookmark,
  },
  {
    name: "bookmark-chevron",
    categories: [IconCategory.DOCUMENT, IconCategory.OTHER],
    tags: [
      "reading",
      "reader",
      "novel",
      "story",
      "placeholder",
      "favorites",
      "favorited",
      "library",
    ],
    Icon: Icon.BookmarkChevron,
  },
  {
    name: "briefcase",
    categories: [IconCategory.BUSINESS],
    tags: ["suitcases", "valises", "baggage", "folders", "portfolios"],
    Icon: Icon.Briefcase,
  },
  {
    name: "briefcase-simple",
    categories: [IconCategory.BUSINESS],
    tags: ["suitcases", "valises", "baggage", "folders", "portfolios"],
    Icon: Icon.BriefcaseSimple,
  },
  {
    name: "calendar-blank",
    categories: [IconCategory.BUSINESS, IconCategory.SYSTEM],
    tags: ["dates", "times", "events", "schedule", "none"],
    Icon: Icon.CalendarBlank,
  },
  {
    name: "calendar-six",
    categories: [IconCategory.BUSINESS, IconCategory.SYSTEM],
    tags: ["dates", "times", "events", "schedule", "6"],
    Icon: Icon.CalendarSix,
  },
  {
    name: "calendar-x",
    categories: [IconCategory.BUSINESS, IconCategory.SYSTEM],
    tags: ["dates", "times", "events", "schedule", "closed", "cancelled"],
    Icon: Icon.CalendarX,
  },
  {
    name: "camera",
    categories: [IconCategory.DEVICE, IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["photography", "pictures", "lens"],
    Icon: Icon.Camera,
  },
  {
    name: "caret-down",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.CaretDown,
  },
  {
    name: "caret-down-circle",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.CaretDownCircle,
  },
  {
    name: "caret-left",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.CaretLeft,
  },
  {
    name: "caret-left-circle",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.CaretLeftCircle,
  },
  {
    name: "caret-right",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.CaretRight,
  },
  {
    name: "caret-right-circle",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.CaretRightCircle,
  },
  {
    name: "caret-up",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.CaretUp,
  },
  {
    name: "caret-up-circle",
    categories: [IconCategory.OTHER],
    tags: ["directional", "pointer", "pointing", "arrowhead"],
    Icon: Icon.CaretUpCircle,
  },
  {
    name: "cell-signal-full",
    categories: [IconCategory.SYSTEM],
    tags: [
      "wireless",
      "cellular",
      "phone",
      "mobile",
      "network",
      "connection",
      "connectivity",
    ],
    Icon: Icon.CellSignalFull,
  },
  {
    name: "cell-signal-high",
    categories: [IconCategory.SYSTEM],
    tags: [
      "wireless",
      "cellular",
      "phone",
      "mobile",
      "network",
      "connection",
      "connectivity",
    ],
    Icon: Icon.CellSignalHigh,
  },
  {
    name: "cell-signal-low",
    categories: [IconCategory.SYSTEM],
    tags: [
      "wireless",
      "cellular",
      "phone",
      "mobile",
      "network",
      "connection",
      "connectivity",
    ],
    Icon: Icon.CellSignalLow,
  },
  {
    name: "cell-signal-medium",
    categories: [IconCategory.SYSTEM],
    tags: [
      "wireless",
      "cellular",
      "phone",
      "mobile",
      "network",
      "connection",
      "connectivity",
    ],
    Icon: Icon.CellSignalMedium,
  },
  {
    name: "cell-signal-none",
    categories: [IconCategory.SYSTEM],
    tags: [
      "wireless",
      "cellular",
      "phone",
      "mobile",
      "network",
      "connection",
      "connectivity",
    ],
    Icon: Icon.CellSignalNone,
  },
  {
    name: "chart-bar-horizontal",
    categories: [IconCategory.BUSINESS, IconCategory.FINANCE],
    tags: ["graphs", "graphing", "charts", "histogram", "analyze", "analysis"],
    Icon: Icon.ChartBarHorizontal,
  },
  {
    name: "chart-pie",
    categories: [IconCategory.BUSINESS, IconCategory.FINANCE],
    tags: ["graphs", "graphing", "charts", "circle", "analyze", "analysis"],
    Icon: Icon.ChartPie,
  },
  {
    name: "chart-pie-slice",
    categories: [IconCategory.BUSINESS, IconCategory.FINANCE],
    tags: ["graphs", "graphing", "charts", "circle", "analyze", "analysis"],
    Icon: Icon.ChartPieSlice,
  },
  {
    name: "chat-circle",
    categories: [IconCategory.COMMUNICATION],
    tags: ["send", "sent", "messages", "messaging", "sms", "texting", "round"],
    Icon: Icon.ChatCircle,
  },
  {
    name: "chat-circle-dots",
    categories: [IconCategory.COMMUNICATION],
    tags: ["send", "sent", "messages", "messaging", "sms", "texting", "round"],
    Icon: Icon.ChatCircleDots,
  },
  {
    name: "chat-circle-text",
    categories: [IconCategory.COMMUNICATION],
    tags: ["send", "sent", "messages", "messaging", "sms", "texting", "round"],

    Icon: Icon.ChatCircleText,
  },
  {
    name: "chat-circle-two",
    categories: [IconCategory.COMMUNICATION],
    tags: ["send", "sent", "messages", "messaging", "sms", "texting", "round"],

    Icon: Icon.ChatCircleTwo,
  },
  {
    name: "chat-rectangle",
    categories: [IconCategory.COMMUNICATION],
    tags: ["send", "sent", "messages", "messaging", "sms", "texting", "square"],
    Icon: Icon.ChatRectangle,
  },
  {
    name: "chat-rectangle-dots",
    categories: [IconCategory.COMMUNICATION],
    tags: ["send", "sent", "messages", "messaging", "sms", "texting", "square"],

    Icon: Icon.ChatRectangleDots,
  },
  {
    name: "chat-rectangle-text",
    categories: [IconCategory.COMMUNICATION],
    tags: ["send", "sent", "messages", "messaging", "sms", "texting", "square"],

    Icon: Icon.ChatRectangleText,
  },
  {
    name: "chat-rectangle-two",
    categories: [IconCategory.COMMUNICATION],
    tags: ["send", "sent", "messages", "messaging", "sms", "texting", "square"],

    Icon: Icon.ChatRectangleTwo,
  },
  {
    name: "chat-teardrop",
    categories: [IconCategory.COMMUNICATION],
    tags: ["send", "sent", "messages", "messaging", "sms", "texting"],
    Icon: Icon.ChatTeardrop,
  },
  {
    name: "chat-teardrop-dots",
    categories: [IconCategory.COMMUNICATION],
    tags: ["send", "sent", "messages", "messaging", "sms", "texting"],
    Icon: Icon.ChatTeardropDots,
  },
  {
    name: "chat-teardrop-text",
    categories: [IconCategory.COMMUNICATION],
    tags: ["send", "sent", "messages", "messaging", "sms", "texting"],
    Icon: Icon.ChatTeardropText,
  },
  {
    name: "chat-teardrop-two",
    categories: [IconCategory.COMMUNICATION],
    tags: ["send", "sent", "messages", "messaging", "sms", "texting"],
    Icon: Icon.ChatTeardropTwo,
  },
  {
    name: "check-circle",
    categories: [IconCategory.BUSINESS, IconCategory.SYSTEM],
    tags: ["todo", "to-do", "list", "checkbox", "round"],
    Icon: Icon.CheckCircle,
  },
  {
    name: "check-square",
    categories: [IconCategory.BUSINESS, IconCategory.SYSTEM],
    tags: ["todo", "to-do", "list", "checkbox", "rectangle"],
    Icon: Icon.CheckSquare,
  },
  {
    name: "check-square-offset",
    categories: [IconCategory.BUSINESS, IconCategory.SYSTEM],
    tags: ["todo", "to-do", "list", "checkbox", "rectangle"],
    Icon: Icon.CheckSquareOffset,
  },
  {
    name: "circle",
    categories: [IconCategory.OTHER],
    tags: ["round", "shapes", "polygons"],
    Icon: Icon.Circle,
  },
  {
    name: "circle-split",
    categories: [IconCategory.DESIGN, IconCategory.EDITOR, IconCategory.OTHER],
    tags: ["round", "shapes", "polygons", "contrast", "brightness"],
    Icon: Icon.CircleSplit,
  },
  {
    name: "circle-split-angled",
    categories: [IconCategory.DESIGN, IconCategory.EDITOR, IconCategory.OTHER],
    tags: ["round", "shapes", "polygons", "contrast", "brightness"],
    Icon: Icon.CircleSplitAngled,
  },
  {
    name: "circles-concentric",
    categories: [IconCategory.OTHER],
    tags: ["round", "shapes", "polygons", "bullseye"],
    Icon: Icon.CirclesConcentric,
  },
  {
    name: "circles-four",
    categories: [IconCategory.OTHER],
    tags: ["round", "shapes", "polygons", "4"],
    Icon: Icon.CirclesFour,
  },
  {
    name: "circles-three",
    categories: [IconCategory.OTHER],
    tags: ["round", "shapes", "polygons", "3"],
    Icon: Icon.CirclesThree,
  },
  {
    name: "clock",
    categories: [IconCategory.SYSTEM],
    tags: ["times", "timer", "alarm", "schedule", "events", "watch"],
    Icon: Icon.Clock,
  },
  {
    name: "clock-alt",
    categories: [IconCategory.SYSTEM],
    tags: ["times", "timer", "alarm", "schedule", "events", "watch"],
    Icon: Icon.ClockAlt,
  },
  {
    name: "cloud",
    categories: [
      IconCategory.BUSINESS,
      IconCategory.SYSTEM,
      IconCategory.WEATHER,
    ],
    tags: [
      "serverless",
      "backup",
      "storage",
      "meteorology",
      "cloudy",
      "overcast",
    ],
    Icon: Icon.Cloud,
  },
  {
    name: "cloud-arrow-down",
    categories: [IconCategory.BUSINESS, IconCategory.SYSTEM],
    tags: ["serverless", "backup", "storage", "download"],
    Icon: Icon.CloudArrowDown,
  },
  {
    name: "cloud-arrow-up",
    categories: [IconCategory.BUSINESS, IconCategory.SYSTEM],
    tags: ["serverless", "backup", "storage", "upload"],
    Icon: Icon.CloudArrowUp,
  },
  {
    name: "cloud-lightning",
    categories: [IconCategory.WEATHER],
    tags: ["meteorology", "cloudy", "overcast", "stormy", "thunderstorm"],
    Icon: Icon.CloudLightning,
  },
  {
    name: "cloud-rain",
    categories: [IconCategory.WEATHER],
    tags: ["meteorology", "cloudy", "rainy", "raining", "stormy", "rainstorm"],
    Icon: Icon.CloudRain,
  },
  {
    name: "cloud-snow",
    categories: [IconCategory.WEATHER],
    tags: ["meteorology", "cloudy", "snowy", "snowing", "stormy", "snowstorm"],
    Icon: Icon.CloudSnow,
  },
  {
    name: "command",
    categories: [IconCategory.EDITOR, IconCategory.SYSTEM],
    tags: [
      "apple",
      "keyboard",
      "shortcut",
      "modifier",
      "looped square",
      "Bowen knot",
      "Saint John's Arms",
    ],
    Icon: Icon.Command,
  },
  {
    name: "copy",
    categories: [IconCategory.EDITOR, IconCategory.SYSTEM],
    tags: ["duplicated", "copied"],
    Icon: Icon.Copy,
  },
  {
    name: "credit-card",
    categories: [IconCategory.BUSINESS, IconCategory.FINANCE],
    tags: [
      "debit",
      "visa",
      "mastercard",
      "payment",
      "paying",
      "purchase",
      "swipe",
    ],
    Icon: Icon.CreditCard,
  },
  {
    name: "cube",
    categories: [IconCategory.DESIGN, IconCategory.OTHER],
    tags: ["square", "box", "3d", "volume", "blocks"],
    Icon: Icon.Cube,
  },
  {
    name: "diamond",
    categories: [IconCategory.OTHER],
    tags: ["rectangle", "shapes", "polygons", "diamonds", "suits", "cards"],
    Icon: Icon.Diamond,
  },
  {
    name: "divide",
    categories: [
      IconCategory.DEVELOPMENT,
      IconCategory.FINANCE,
      IconCategory.OTHER,
    ],
    tags: [
      "division",
      "divisor",
      "dividend",
      "quotient",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.Divide,
  },
  {
    name: "dots-nine",
    categories: [IconCategory.OTHER],
    tags: ["round", "circles", "shapes", "polygons", "9"],
    Icon: Icon.DotsNine,
  },
  {
    name: "dribbble",
    categories: [IconCategory.BRAND, IconCategory.HEALTH],
    tags: ["round", "basketball", "design"],
    Icon: Icon.Dribbble,
  },
  {
    name: "envelope",
    categories: [IconCategory.COMMUNICATION],
    tags: ["mail", "email", "send", "sent", "message"],
    Icon: Icon.Envelope,
  },
  {
    name: "envelope-simple",
    categories: [IconCategory.COMMUNICATION],
    tags: ["mail", "email", "send", "sent", "message"],
    Icon: Icon.EnvelopeSimple,
  },
  {
    name: "equals",
    categories: [
      IconCategory.DEVELOPMENT,
      IconCategory.FINANCE,
      IconCategory.OTHER,
    ],
    tags: [
      "equality",
      "equivalent",
      "equivalence",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.Equals,
  },
  {
    name: "eye",
    categories: [IconCategory.OTHER],
    tags: ["visible", "hidden", "show", "hide", "visibility"],
    Icon: Icon.Eye,
  },
  {
    name: "eye-closed",
    categories: [IconCategory.OTHER],
    tags: ["visible", "hidden", "show", "hide", "visibility", "invisible"],
    Icon: Icon.EyeClosed,
  },
  {
    name: "eye-slash",
    categories: [IconCategory.OTHER],
    tags: [
      "visible",
      "hidden",
      "show",
      "hide",
      "visibility",
      "invisible",
      "eyelashes",
    ],
    Icon: Icon.EyeSlash,
  },
  {
    name: "fast-forward",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["seek", "scrub", "scan", "ahead"],
    Icon: Icon.FastForward,
  },
  {
    name: "file",
    categories: [IconCategory.DOCUMENT, IconCategory.EDITOR],
    tags: ["documents", "files", "save", "write"],
    Icon: Icon.File,
  },
  {
    name: "file-arrow-down",
    categories: [IconCategory.DOCUMENT, IconCategory.EDITOR],
    tags: [
      "documents",
      "files",
      "save",
      "write",
      "download",
      "directional",
      "pointer",
      "pointing",
      "arrowhead",
    ],
    Icon: Icon.FileArrowDown,
  },
  {
    name: "file-text",
    categories: [IconCategory.DOCUMENT, IconCategory.EDITOR],
    tags: ["documents", "files", "save", "write"],
    Icon: Icon.FileText,
  },
  {
    name: "file-x",
    categories: [IconCategory.DOCUMENT, IconCategory.EDITOR],
    tags: ["documents", "files", "cancelled", "deleted", "removed", "errors"],
    Icon: Icon.FileX,
  },
  {
    name: "fingerprint",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: [
      "security",
      "secured",
      "authentication",
      "authenticated",
      "login",
      "locked",
      "biometrics",
      "encrypted",
      "encryption",
    ],
    Icon: Icon.Fingerprint,
  },
  {
    name: "fingerprint-dense",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: [
      "security",
      "secured",
      "authentication",
      "authenticated",
      "login",
      "locked",
      "biometrics",
      "encrypted",
      "encryption",
    ],
    Icon: Icon.FingerprintDense,
  },
  {
    name: "floppy-disk",
    categories: [
      IconCategory.DOCUMENT,
      IconCategory.EDITOR,
      IconCategory.SYSTEM,
    ],
    tags: [
      "directory",
      "directories",
      "folders",
      "documents",
      "files",
      "save",
      "write",
    ],
    Icon: Icon.FloppyDisk,
  },
  {
    name: "folder",
    categories: [
      IconCategory.DOCUMENT,
      IconCategory.EDITOR,
      IconCategory.SYSTEM,
    ],
    tags: ["directory", "directories", "files", "folders"],
    Icon: Icon.Folder,
  },
  {
    name: "folder-add",
    categories: [
      IconCategory.DOCUMENT,
      IconCategory.EDITOR,
      IconCategory.SYSTEM,
    ],
    tags: ["directory", "directories", "files", "create", "new folders"],
    Icon: Icon.FolderAdd,
  },
  {
    name: "folder-dip",
    categories: [
      IconCategory.DOCUMENT,
      IconCategory.EDITOR,
      IconCategory.SYSTEM,
    ],
    tags: ["directory", "directories", "files", "folders"],
    Icon: Icon.FolderDip,
  },
  {
    name: "folder-open",
    categories: [
      IconCategory.DOCUMENT,
      IconCategory.EDITOR,
      IconCategory.SYSTEM,
    ],
    tags: ["directory", "directories", "files", "folders", "load"],
    Icon: Icon.FolderOpen,
  },
  {
    name: "folder-simple",
    categories: [
      IconCategory.DOCUMENT,
      IconCategory.EDITOR,
      IconCategory.SYSTEM,
    ],
    tags: ["directory", "directories", "files", "folders"],
    Icon: Icon.FolderSimple,
  },
  {
    name: "frame-target",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: [],
    Icon: Icon.FrameTarget,
  },
  {
    name: "gear-eight",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: [
      "8",
      "settings",
      "setup",
      "preferences",
      "cogs",
      "gears",
      "machinery",
      "mechanical",
    ],
    Icon: Icon.GearEight,
  },
  {
    name: "gear-six",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: [
      "6",
      "settings",
      "setup",
      "preferences",
      "cogs",
      "gears",
      "machinery",
      "mechanical",
    ],
    Icon: Icon.GearSix,
  },
  {
    name: "globe",
    categories: [IconCategory.MAP],
    tags: [
      "world",
      "global",
      "planet",
      "circle",
      "round",
      "internationalization",
      "languages",
      "country",
      "countries",
    ],
    Icon: Icon.Globe,
  },
  {
    name: "globe-simple",
    categories: [IconCategory.MAP],
    tags: [
      "world",
      "global",
      "planet",
      "circle",
      "round",
      "internationalization",
      "languages",
      "country",
      "countries",
    ],
    Icon: Icon.GlobeSimple,
  },
  {
    name: "google-play",
    categories: [IconCategory.SYSTEM, IconCategory.MEDIA],
    tags: [
      "games",
      "apps",
      "applications",
      "play store",
      "app store",
      "phone",
      "mobile",
      "android",
    ],
    Icon: Icon.GooglePlay,
  },
  {
    name: "grid-four",
    categories: [IconCategory.SYSTEM],
    tags: [
      "4",
      "apps",
      "applications",
      "squares",
      "tiles",
      "cells",
      "tables",
      "tabular",
      "spreadsheets",
      "excel",
    ],
    Icon: Icon.GridFour,
  },
  {
    name: "handbag",
    categories: [IconCategory.BUSINESS],
    tags: ["suitcases", "valises", "baggage", "purses"],
    Icon: Icon.Handbag,
  },
  {
    name: "hash",
    categories: [IconCategory.COMMUNICATION, IconCategory.OTHER],
    tags: [
      "hashtag",
      "octothorpe",
      "pound sign",
      "number sign",
      "tic-tac-toe",
      "symbol",
    ],
    Icon: Icon.Hash,
  },
  {
    name: "hash-straight",
    categories: [IconCategory.COMMUNICATION, IconCategory.OTHER],
    tags: [
      "hashtag",
      "octothorpe",
      "pound sign",
      "number sign",
      "tic-tac-toe",
      "symbol",
    ],
    Icon: Icon.HashStraight,
  },
  {
    name: "heart",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.DESIGN,
      IconCategory.HEALTH,
      IconCategory.OTHER,
    ],
    tags: [
      "wellness",
      "love",
      "healthy",
      "like",
      "favorites",
      "favorited",
      "suits",
      "cards",
    ],
    Icon: Icon.Heart,
  },
  {
    name: "heart-straight",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.DESIGN,
      IconCategory.HEALTH,
      IconCategory.OTHER,
    ],
    tags: [
      "wellness",
      "love",
      "healthy",
      "like",
      "favorites",
      "favorited",
      "suits",
      "cards",
    ],
    Icon: Icon.HeartStraight,
  },
  {
    name: "hexagon",
    categories: [IconCategory.OTHER],
    tags: ["6", "shapes", "polygons"],
    Icon: Icon.Hexagon,
  },
  {
    name: "hourglass",
    categories: [IconCategory.SYSTEM],
    tags: [
      "times",
      "timer",
      "alarms",
      "clock",
      "schedule",
      "events",
      "waiting",
    ],
    Icon: Icon.Hourglass,
  },
  {
    name: "hourglass-high",
    categories: [IconCategory.SYSTEM],
    tags: [
      "times",
      "timer",
      "alarms",
      "clock",
      "schedule",
      "events",
      "waiting",
    ],
    Icon: Icon.HourglassHigh,
  },
  {
    name: "hourglass-low",
    categories: [IconCategory.SYSTEM],
    tags: [
      "times",
      "timer",
      "alarms",
      "clock",
      "schedule",
      "events",
      "waiting",
    ],
    Icon: Icon.HourglassLow,
  },
  {
    name: "hourglass-medium",
    categories: [IconCategory.SYSTEM],
    tags: [
      "times",
      "timer",
      "alarms",
      "clock",
      "schedule",
      "events",
      "waiting",
    ],
    Icon: Icon.HourglassMedium,
  },
  // {
  //   name: "horse",
  //   categories: [IconCategory.HEALTH, IconCategory.OTHER],
  //   tags: ["animals", "equestrian", "chess", "knight", "games", "sports"],
  //   Icon: Icon.Horse,
  // },
  {
    name: "house",
    categories: [IconCategory.MAP, IconCategory.OTHER],
    tags: ["homes", "buildings", "places", "locations"],
    Icon: Icon.House,
  },
  {
    name: "house-line",
    categories: [IconCategory.MAP, IconCategory.OTHER],
    tags: ["homes", "buildings", "places", "locations"],
    Icon: Icon.HouseLine,
  },
  {
    name: "house-round-door",
    categories: [IconCategory.MAP, IconCategory.OTHER],
    tags: ["homes", "buildings", "places", "locations"],
    Icon: Icon.HouseRoundDoor,
  },
  {
    name: "house-simple",
    categories: [IconCategory.MAP, IconCategory.OTHER],
    tags: ["homes", "buildings", "places", "locations"],
    Icon: Icon.HouseSimple,
  },
  {
    name: "info-circle",
    categories: [IconCategory.SYSTEM],
    tags: ["information", "help"],
    Icon: Icon.InfoCircle,
  },
  {
    name: "intersect",
    categories: [IconCategory.DESIGN, IconCategory.EDITOR],
    tags: [
      "round",
      "joining",
      "union",
      "merged",
      "merging",
      "intersecting",
      "intersection",
    ],
    Icon: Icon.Intersect,
  },
  {
    name: "lightning",
    categories: [
      IconCategory.WEATHER,
      IconCategory.SYSTEM,
      IconCategory.DEVICE,
    ],
    tags: [
      "meteorology",
      "stormy",
      "thunderstorm",
      "thunderbolt",
      "charged",
      "charger",
      "charging",
      "power",
    ],
    Icon: Icon.Lightning,
  },
  {
    name: "lines-three",
    categories: [IconCategory.SYSTEM],
    tags: ["3", "hamburger menu", "overflow menu", "sidebar"],
    Icon: Icon.LinesThree,
  },
  {
    name: "link",
    categories: [IconCategory.OTHER],
    tags: ["anchor", "hyperlink", "hypertext", "chains", "chained"],
    Icon: Icon.Link,
  },
  {
    name: "lock-dot",
    categories: [IconCategory.OTHER],
    tags: [
      "padlock",
      "security",
      "secured",
      "authentication",
      "authenticated",
      "login",
      "locked",
      "encrypted",
      "encryption",
    ],
    Icon: Icon.LockDot,
  },
  {
    name: "lock-grooves",
    categories: [IconCategory.OTHER],
    tags: [
      "padlock",
      "security",
      "secured",
      "authentication",
      "authenticated",
      "login",
      "locked",
      "encrypted",
      "encryption",
    ],
    Icon: Icon.LockGrooves,
  },
  {
    name: "lock-key",
    categories: [IconCategory.OTHER],
    tags: [
      "padlock",
      "security",
      "secured",
      "authentication",
      "authenticated",
      "login",
      "locked",
      "encrypted",
      "encryption",
    ],
    Icon: Icon.LockKey,
  },
  {
    name: "lock-open-dot",
    categories: [IconCategory.OTHER],
    tags: [
      "padlock",
      "security",
      "unsecured",
      "authentication",
      "unauthenticated",
      "login",
      "unlocked",
      "unencrypted",
      "encryption",
    ],
    Icon: Icon.LockOpenDot,
  },
  {
    name: "lock-open-key",
    categories: [IconCategory.OTHER],
    tags: [
      "padlock",
      "security",
      "unsecured",
      "authentication",
      "unauthenticated",
      "login",
      "unlocked",
      "unencrypted",
      "encryption",
    ],
    Icon: Icon.LockOpenKey,
  },
  {
    name: "magnifying-glass",
    categories: [IconCategory.EDITOR, IconCategory.SYSTEM],
    tags: ["search", "find", "locate", "query", "inspect"],
    Icon: Icon.MagnifyingGlass,
  },
  {
    name: "magnifying-glass-minus",
    categories: [IconCategory.EDITOR, IconCategory.SYSTEM],
    tags: ["search", "find", "locate", "query", "inspect", "zoom out"],
    Icon: Icon.MagnifyingGlassMinus,
  },
  {
    name: "magnifying-glass-plus",
    categories: [IconCategory.EDITOR, IconCategory.SYSTEM],
    tags: ["search", "find", "locate", "query", "inspect", "zoom in"],
    Icon: Icon.MagnifyingGlassPlus,
  },
  {
    name: "map-pin",
    categories: [IconCategory.MAP],
    tags: ["maps", "places", "markers", "pins", "locations"],
    Icon: Icon.MapPin,
  },
  {
    name: "map-pin-line",
    categories: [IconCategory.MAP],
    tags: ["maps", "places", "markers", "pins", "locations"],
    Icon: Icon.MapPinLine,
  },
  {
    name: "map-trifold",
    categories: [IconCategory.MAP],
    tags: ["maps", "places", "locations", "cartography"],
    Icon: Icon.MapTrifold,
  },
  {
    name: "math",
    categories: [
      IconCategory.DEVELOPMENT,
      IconCategory.FINANCE,
      IconCategory.OTHER,
    ],
    tags: [
      "addition",
      "sum",
      "subtraction",
      "difference",
      "multiply",
      "multiplication",
      "product",
      "divide",
      "division",
      "divisor",
      "dividend",
      "quotient",
      "equals",
      "equality",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.Math,
  },
  {
    name: "medium",
    categories: [IconCategory.BRAND],
    tags: ["reading", "writing", "news"],
    Icon: Icon.Medium,
  },
  {
    name: "microphone",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.DEVICE,
      IconCategory.MEDIA,
      IconCategory.SYSTEM,
    ],
    tags: ["microphone", "audio", "recording", "music", "sound", "podcast"],
    Icon: Icon.Microphone,
  },
  {
    name: "microphone-off",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.DEVICE,
      IconCategory.MEDIA,
      IconCategory.SYSTEM,
    ],
    tags: ["microphone", "audio", "recording", "music", "sound", "podcast"],
    Icon: Icon.MicrophoneOff,
  },
  {
    name: "minus",
    categories: [
      IconCategory.DEVELOPMENT,
      IconCategory.FINANCE,
      IconCategory.OTHER,
    ],
    tags: [
      "subtraction",
      "difference",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.Minus,
  },
  {
    name: "minus-circle",
    categories: [
      IconCategory.DEVELOPMENT,
      IconCategory.FINANCE,
      IconCategory.OTHER,
    ],
    tags: [
      "subtraction",
      "difference",
      "mathematics",
      "arithmetic",
      "calculator",
      "round",
    ],
    Icon: Icon.MinusCircle,
  },
  {
    name: "moon",
    categories: [IconCategory.OTHER, IconCategory.WEATHER, IconCategory.SYSTEM],
    tags: [
      "night",
      "evening",
      "clear",
      "sleep",
      "snooze",
      "night mode",
      "dark mode",
    ],
    Icon: Icon.Moon,
  },
  {
    name: "music-notes",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["songs", "audio", "playlist", "albums"],
    Icon: Icon.Notes,
  },
  {
    name: "music-notes-eighth",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["songs", "audio", "playlist", "albums"],
    Icon: Icon.NotesEighth,
  },
  {
    name: "music-notes-eighth-beamed",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["songs", "audio", "playlist", "albums"],
    Icon: Icon.NotesEighthBeamed,
  },
  {
    name: "music-notes-sixteenth",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["songs", "audio", "playlist", "albums"],
    Icon: Icon.NotesSixteenth,
  },
  {
    name: "music-notes-sixteenth-beamed",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["songs", "audio", "playlist", "albums"],
    Icon: Icon.NotesSixteenthsBeamed,
  },
  {
    name: "number-zero",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "0",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.Zero,
  },
  {
    name: "number-zero-circle",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "0",
      "round",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.ZeroCircle,
  },
  {
    name: "number-zero-square",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "0",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.ZeroSquare,
  },
  {
    name: "number-one",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "1",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.One,
  },
  {
    name: "number-one-circle",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "1",
      "round",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.OneCircle,
  },
  {
    name: "number-one-square",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "1",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.OneSquare,
  },
  {
    name: "number-two",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "2",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.Two,
  },
  {
    name: "number-two-circle",
    categories: [IconCategory.DESIGN],
    tags: [
      "2",
      "round",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.TwoCircle,
  },
  {
    name: "number-two-square",
    categories: [IconCategory.DESIGN],
    tags: [
      "2",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.TwoSquare,
  },
  {
    name: "number-three",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "3",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.Three,
  },
  {
    name: "number-three-circle",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "3",
      "round",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.ThreeCircle,
  },
  {
    name: "number-three-square",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "3",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.ThreeSquare,
  },
  {
    name: "number-four",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "4",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.Four,
  },
  {
    name: "number-four-circle",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "4",
      "round",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.FourCircle,
  },
  {
    name: "number-four-square",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "4",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.FourSquare,
  },
  {
    name: "number-five",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "5",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.Five,
  },
  {
    name: "number-five-circle",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "5",
      "round",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.FiveCircle,
  },
  {
    name: "number-five-square",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "5",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.FiveSquare,
  },
  {
    name: "number-six",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "6",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.Six,
  },
  {
    name: "number-six-circle",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "6",
      "round",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.SixCircle,
  },
  {
    name: "number-six-square",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "6",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.SixSquare,
  },
  {
    name: "number-seven",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "7",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.Seven,
  },
  {
    name: "number-seven-circle",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "7",
      "round",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.SevenCircle,
  },
  {
    name: "number-seven-square",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "7",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.SevenSquare,
  },

  {
    name: "number-eight",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "8",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.Eight,
  },
  {
    name: "number-eight-circle",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "8",
      "round",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.EightCircle,
  },
  {
    name: "number-eight-square",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "8",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.EightSquare,
  },
  {
    name: "number-nine",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "9",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.Nine,
  },
  {
    name: "number-nine-circle",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "9",
      "round",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.NineCircle,
  },
  {
    name: "number-nine-square",
    categories: [IconCategory.FINANCE, IconCategory.OTHER],
    tags: [
      "9",
      "numbers",
      "numerals",
      "digits",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.NineSquare,
  },

  {
    name: "note-blank-fold",
    categories: [IconCategory.DOCUMENT, IconCategory.EDITOR],
    tags: ["notes", "note-taking", "post-it", "reminders"],
    Icon: Icon.NoteBlankFold,
  },
  {
    name: "note-pen",
    categories: [IconCategory.DOCUMENT, IconCategory.EDITOR],
    tags: ["notes", "note-taking", "post-it", "reminders"],
    Icon: Icon.NotePen,
  },
  {
    name: "note-pencil",
    categories: [IconCategory.DOCUMENT, IconCategory.EDITOR],
    tags: ["notes", "note-taking", "post-it", "reminders"],
    Icon: Icon.NotePencil,
  },
  {
    name: "note-text-long",
    categories: [IconCategory.DOCUMENT, IconCategory.EDITOR],
    tags: ["notes", "note-taking", "post-it", "reminders"],
    Icon: Icon.NoteTextLong,
  },
  {
    name: "note-text-long-fold",
    categories: [IconCategory.DOCUMENT, IconCategory.EDITOR],
    tags: ["notes", "note-taking", "post-it", "reminders"],
    Icon: Icon.NoteTextLongFold,
  },
  {
    name: "note-text-short",
    categories: [IconCategory.DOCUMENT, IconCategory.EDITOR],
    tags: ["notes", "note-taking", "post-it", "reminders"],
    Icon: Icon.NoteTextShort,
  },
  {
    name: "nut-six",
    categories: [IconCategory.OTHER],
    tags: ["bolts", "screws", "machinery", "tools", "hexagon"],
    Icon: Icon.NutSix,
  },
  {
    name: "octagon",
    categories: [IconCategory.OTHER],
    tags: ["8", "shapes", "polygons"],
    Icon: Icon.Octagon,
  },
  {
    name: "overflow-horizontal",
    categories: [IconCategory.SYSTEM],
    tags: [
      "hamburger menu",
      "overflow menu",
      "sidebar",
      "ellipsis",
      "ellipses",
    ],
    Icon: Icon.OverflowHorizontal,
  },
  {
    name: "overflow-horizontal-circle",
    categories: [IconCategory.SYSTEM],
    tags: [
      "hamburger menu",
      "overflow menu",
      "sidebar",
      "ellipsis",
      "ellipses",
    ],
    Icon: Icon.OverflowHorizontalCircle,
  },
  {
    name: "overflow-horizontal-outline",
    categories: [IconCategory.SYSTEM],
    tags: [
      "hamburger menu",
      "overflow menu",
      "sidebar",
      "ellipsis",
      "ellipses",
    ],
    Icon: Icon.OverflowHorizontalOutline,
  },
  {
    name: "overflow-vertical",
    categories: [IconCategory.SYSTEM],
    tags: [
      "hamburger menu",
      "overflow menu",
      "sidebar",
      "ellipsis",
      "ellipses",
    ],
    Icon: Icon.OverflowVertical,
  },
  {
    name: "overflow-vertical-circle",
    categories: [IconCategory.SYSTEM],
    tags: [
      "hamburger menu",
      "overflow menu",
      "sidebar",
      "ellipsis",
      "ellipses",
    ],
    Icon: Icon.OverflowVerticalCircle,
  },
  {
    name: "overflow-vertical-outline",
    categories: [IconCategory.SYSTEM],
    tags: [
      "hamburger menu",
      "overflow menu",
      "sidebar",
      "ellipsis",
      "ellipses",
    ],
    Icon: Icon.OverflowVerticalOutline,
  },
  {
    name: "package",
    categories: [
      IconCategory.BUSINESS,
      IconCategory.DEVELOPMENT,
      IconCategory.OTHER,
    ],
    tags: ["packages", "bundles", "library", "libraries", "shipping"],
    Icon: Icon.Package,
  },
  {
    name: "paint-bucket",
    categories: [IconCategory.DESIGN, IconCategory.EDITOR, IconCategory.OTHER],
    tags: ["paintbucket", "fill"],
    Icon: Icon.PaintBucket,
  },
  {
    name: "paperclip",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.EDITOR,
      IconCategory.OTHER,
    ],
    tags: ["attachments", "email", "office"],
    Icon: Icon.Paperclip,
  },
  {
    name: "paper-plane",
    categories: [IconCategory.COMMUNICATION, IconCategory.OTHER],
    tags: ["messages", "messaging", "send", "sent", "email", "toys", "games"],
    Icon: Icon.PaperPlane,
  },
  {
    name: "pause",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "resume", "start", "stop"],
    Icon: Icon.Pause,
  },
  {
    name: "pause-circle",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "resume", "start", "stop", "round"],
    Icon: Icon.PauseCircle,
  },
  {
    name: "pen",
    categories: [IconCategory.DESIGN, IconCategory.EDITOR],
    tags: ["ink", "write", "writing", "editing", "sign", "signature"],
    Icon: Icon.Pen,
  },
  {
    name: "pencil-line",
    categories: [IconCategory.DESIGN, IconCategory.EDITOR],
    tags: ["write", "writing", "editing", "sign", "signature"],
    Icon: Icon.PencilLine,
  },
  {
    name: "pen-nib",
    categories: [IconCategory.DESIGN, IconCategory.EDITOR],
    tags: [
      "ink",
      "write",
      "writing",
      "editing",
      "sign",
      "signature",
      "fountain pen",
      "illustrator",
    ],
    Icon: Icon.PenNib,
  },
  {
    name: "percent",
    categories: [
      IconCategory.DEVELOPMENT,
      IconCategory.FINANCE,
      IconCategory.OTHER,
    ],
    tags: [
      "percentage",
      "percentile",
      "ratio",
      "delta",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.Percent,
  },
  {
    name: "picture-landscape",
    categories: [IconCategory.DOCUMENT, IconCategory.MEDIA],
    tags: ["photographs", "photography", "wallpapers", "gallery"],
    Icon: Icon.PictureLandscape,
  },
  {
    name: "picture-square",
    categories: [IconCategory.DOCUMENT, IconCategory.MEDIA],
    tags: ["photographs", "photography", "wallpapers", "gallery"],
    Icon: Icon.PictureSquare,
  },
  {
    name: "play",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "resume", "start"],
    Icon: Icon.Play,
  },
  {
    name: "play-circle",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "resume", "start", "round"],
    Icon: Icon.PlayCircle,
  },
  {
    name: "plus",
    categories: [
      IconCategory.DEVELOPMENT,
      IconCategory.FINANCE,
      IconCategory.OTHER,
    ],
    tags: ["addition", "sum", "mathematics", "arithmetic", "calculator"],
    Icon: Icon.Plus,
  },
  {
    name: "plus-circle",
    categories: [
      IconCategory.DEVELOPMENT,
      IconCategory.FINANCE,
      IconCategory.OTHER,
    ],
    tags: [
      "addition",
      "sum",
      "mathematics",
      "arithmetic",
      "calculator",
      "round",
    ],
    Icon: Icon.PlusCircle,
  },
  {
    name: "plus-minus",
    categories: [
      IconCategory.DEVELOPMENT,
      IconCategory.FINANCE,
      IconCategory.OTHER,
    ],
    tags: [
      "plus or minus",
      "plus/minus",
      "add/subtract",
      "addition",
      "sum",
      "subtraction",
      "difference",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.PlusMinus,
  },
  {
    name: "power",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: [
      "charged",
      "charger",
      "charging",
      "on",
      "off",
      "on/off",
      "switch",
      "power switch",
    ],
    Icon: Icon.Power,
  },
  {
    name: "printer",
    categories: [
      IconCategory.DEVICE,
      IconCategory.EDITOR,
      IconCategory.DOCUMENT,
    ],
    tags: ["printing"],
    Icon: Icon.Printer,
  },
  {
    name: "prohibit",
    categories: [IconCategory.MAP, IconCategory.SYSTEM, IconCategory.OTHER],
    tags: [
      "forbidden",
      "prohibited",
      "cancelled",
      "prevent",
      "stop",
      "do not enter",
    ],
    Icon: Icon.Prohibit,
  },
  {
    name: "prohibit-inset",
    categories: [IconCategory.MAP, IconCategory.SYSTEM, IconCategory.OTHER],
    tags: [
      "forbidden",
      "prohibited",
      "cancelled",
      "prevent",
      "stop",
      "do not enter",
    ],
    Icon: Icon.ProhibitInset,
  },
  {
    name: "push-pin",
    categories: [IconCategory.MAP, IconCategory.OTHER],
    tags: ["favorites", "favorited", "pushpin"],
    Icon: Icon.PushPin,
  },
  {
    name: "question-mark-circle",
    categories: [IconCategory.SYSTEM],
    tags: ["information", "help", "questions"],
    Icon: Icon.QuestionMarkCircle,
  },
  {
    name: "radical",
    categories: [
      IconCategory.DEVELOPMENT,
      IconCategory.FINANCE,
      IconCategory.OTHER,
    ],
    tags: [
      "radix",
      "radicand",
      "square root",
      "squareroot",
      "mathematics",
      "arithmetic",
      "calculator",
    ],
    Icon: Icon.Radical,
  },
  {
    name: "rectangle",
    categories: [IconCategory.OTHER],
    tags: ["4", "shapes", "polygons", "box"],
    Icon: Icon.Rectangle,
  },
  {
    name: "rewind",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: [
      "music",
      "audio",
      "seek",
      "scrub",
      "scan",
      "back",
      "backwards",
      "reverse",
    ],
    Icon: Icon.Rewind,
  },
  {
    name: "shield",
    categories: [IconCategory.SYSTEM, IconCategory.OTHER],
    tags: [
      "security",
      "secured",
      "defense",
      "defended",
      "authentication",
      "authenticated",
      "guarded",
      "locked",
      "encrypted",
      "encryption",
    ],
    Icon: Icon.Shield,
  },
  {
    name: "shield-check",
    categories: [IconCategory.SYSTEM, IconCategory.OTHER],
    tags: [
      "security",
      "secured",
      "defense",
      "defended",
      "authentication",
      "authenticated",
      "guarded",
      "locked",
      "encrypted",
      "encryption",
    ],
    Icon: Icon.ShieldCheck,
  },
  {
    name: "shield-chevron",
    categories: [IconCategory.SYSTEM, IconCategory.OTHER],
    tags: [
      "security",
      "secured",
      "defense",
      "defended",
      "authentication",
      "authenticated",
      "guarded",
      "locked",
      "encrypted",
      "encryption",
    ],
    Icon: Icon.ShieldChevron,
  },
  {
    name: "shopping-bag",
    categories: [IconCategory.BUSINESS, IconCategory.OTHER],
    tags: ["ecommerce", "market", "buying", "checkout"],
    Icon: Icon.ShoppingBag,
  },
  {
    name: "shopping-bag-open",
    categories: [IconCategory.BUSINESS, IconCategory.OTHER],
    tags: ["ecommerce", "market", "buying", "checkout"],
    Icon: Icon.ShoppingBagOpen,
  },
  {
    name: "shuffle",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "randomize"],
    Icon: Icon.Shuffle,
  },
  {
    name: "shuffle-angular",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "randomize"],
    Icon: Icon.ShuffleAngular,
  },
  {
    name: "skip-back",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: [
      "music",
      "audio",
      "seek",
      "scrub",
      "scan",
      "back",
      "backwards",
      "reverse",
      "previous",
    ],
    Icon: Icon.SkipBack,
  },
  {
    name: "skip-forward",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "seek", "scrub", "scan", "ahead", "next"],
    Icon: Icon.SkipForward,
  },
  {
    name: "sliders-circles",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: [
      "music",
      "audio",
      "faders",
      "equalizer",
      "volume",
      "settings",
      "preferences",
    ],
    Icon: Icon.SlidersCircles,
  },
  {
    name: "sliders-lines",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: [
      "music",
      "audio",
      "faders",
      "equalizer",
      "volume",
      "settings",
      "preferences",
    ],
    Icon: Icon.SlidersLines,
  },
  {
    name: "smiley",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.DESIGN,
      IconCategory.OTHER,
    ],
    tags: ["face", "smiley", "emoji", "happy", "grinning", "smiling"],
    Icon: Icon.Smiley,
  },
  {
    name: "smiley-blank",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.DESIGN,
      IconCategory.OTHER,
    ],
    tags: ["face", "smiley", "emoji", "unimpressed", "no face"],
    Icon: Icon.SmileyBlank,
  },
  {
    name: "smiley-meh",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.DESIGN,
      IconCategory.OTHER,
    ],
    tags: ["face", "smiley", "emoji", "unimpressed", "neutral"],
    Icon: Icon.SmileyMeh,
  },
  {
    name: "smiley-nervous",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.DESIGN,
      IconCategory.OTHER,
    ],
    tags: [
      "face",
      "smiley",
      "emoji",
      "anxious",
      "uncomfortable",
      "uneasy",
      "queasy",
      "sick",
      "ill",
    ],
    Icon: Icon.SmileyNervous,
  },
  {
    name: "smiley-sad",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.DESIGN,
      IconCategory.OTHER,
    ],
    tags: ["face", "smiley", "emoji", "unhappy", "frowning"],
    Icon: Icon.SmileySad,
  },
  {
    name: "smiley-x-eyes",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.DESIGN,
      IconCategory.OTHER,
    ],
    tags: ["face", "smiley", "emoji", "dead", "killed", "unconscious"],
    Icon: Icon.SmileyXEyes,
  },
  {
    name: "speaker-high",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "volume", "sound"],
    Icon: Icon.SpeakerHigh,
  },
  {
    name: "speaker-low",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "volume", "sound"],
    Icon: Icon.SpeakerLow,
  },
  {
    name: "speaker-none",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "muted", "volume", "sound"],
    Icon: Icon.SpeakerNone,
  },
  {
    name: "speaker-simple-high",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "volume", "sound"],
    Icon: Icon.SpeakerSimpleHigh,
  },
  {
    name: "speaker-simple-low",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "volume", "sound"],
    Icon: Icon.SpeakerSimpleLow,
  },
  {
    name: "speaker-simple-none",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "muted", "volume", "sound"],
    Icon: Icon.SpeakerSimpleNone,
  },
  {
    name: "speaker-simple-x",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "muted", "volume", "sound"],
    Icon: Icon.SpeakerSimpleX,
  },
  {
    name: "speaker-simple-slash",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "muted", "volume", "sound"],
    Icon: Icon.SpeakerSimpleSlash,
  },
  {
    name: "speaker-x",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "muted", "volume", "sound"],
    Icon: Icon.SpeakerX,
  },
  {
    name: "speaker-slash",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "muted", "volume", "sound"],
    Icon: Icon.SpeakerSlash,
  },
  {
    name: "square",
    categories: [IconCategory.OTHER],
    tags: ["4", "shapes", "polygons", "box"],
    Icon: Icon.Square,
  },
  {
    name: "squares-four",
    categories: [IconCategory.OTHER],
    tags: ["4", "shapes", "polygons"],
    Icon: Icon.SquaresFour,
  },
  {
    name: "stack-isometric",
    categories: [
      IconCategory.DESIGN,
      IconCategory.DOCUMENT,
      IconCategory.EDITOR,
      IconCategory.OTHER,
    ],
    tags: ["cards", "layers"],
    Icon: Icon.StackIsometric,
  },
  {
    name: "stack-two",
    categories: [
      IconCategory.DESIGN,
      IconCategory.DOCUMENT,
      IconCategory.EDITOR,
      IconCategory.OTHER,
    ],
    tags: ["cards", "layers"],
    Icon: Icon.StackTwo,
  },
  {
    name: "star",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.MAP,
      IconCategory.OTHER,
    ],
    tags: ["rate", "ratings", "favorites", "favorited"],
    Icon: Icon.Star,
  },
  {
    name: "stop",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio"],
    Icon: Icon.Stop,
  },
  {
    name: "stop-circle",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["music", "audio", "round"],
    Icon: Icon.StopCircle,
  },
  {
    name: "sun",
    categories: [IconCategory.OTHER, IconCategory.WEATHER, IconCategory.SYSTEM],
    tags: [
      "day",
      "daytime",
      "daylight",
      "clear",
      "sunny",
      "sunshine",
      "light mode",
    ],
    Icon: Icon.Sun,
  },
  {
    name: "sun-dots",
    categories: [IconCategory.OTHER, IconCategory.WEATHER, IconCategory.SYSTEM],
    tags: [
      "day",
      "daytime",
      "daylight",
      "clear",
      "sunny",
      "sunshine",
      "light mode",
    ],
    Icon: Icon.SunDots,
  },
  {
    name: "table",
    categories: [
      IconCategory.BUSINESS,
      IconCategory.FINANCE,
      IconCategory.EDITOR,
    ],
    tags: ["tables", "tabular", "speadsheets", "excel"],
    Icon: Icon.Table,
  },
  {
    name: "tag",
    categories: [
      IconCategory.BUSINESS,
      IconCategory.DEVELOPMENT,
      IconCategory.OTHER,
    ],
    tags: ["tags", "hashtag", "labels"],
    Icon: Icon.Tag,
  },
  {
    name: "text-center",
    categories: [IconCategory.DESIGN, IconCategory.EDITOR],
    tags: ["text alignment", "align center", "centered"],
    Icon: Icon.TextCenter,
  },
  {
    name: "text-justify",
    categories: [IconCategory.DESIGN, IconCategory.EDITOR],
    tags: ["text alignment", "justified"],
    Icon: Icon.TextJustify,
  },
  {
    name: "text-left",
    categories: [IconCategory.DESIGN, IconCategory.EDITOR],
    tags: ["text alignment", "align left"],
    Icon: Icon.TextLeft,
  },
  {
    name: "text-right",
    categories: [IconCategory.DESIGN, IconCategory.EDITOR],
    tags: ["text alignment", "align right"],
    Icon: Icon.TextRight,
  },
  {
    name: "ticket",
    categories: [IconCategory.BUSINESS, IconCategory.OTHER],
    tags: ["ticketstub", "movie ticket"],
    Icon: Icon.Ticket,
  },
  {
    name: "tote",
    categories: [IconCategory.BUSINESS],
    tags: ["suitcases", "valises", "baggage", "tote-bag", "portfolios"],
    Icon: Icon.Tote,
  },
  {
    name: "translate",
    categories: [IconCategory.COMMUNICATION, IconCategory.SYSTEM],
    tags: ["translation", "languages", "internationalization", "speech"],
    Icon: Icon.Translate,
  },
  {
    name: "trash",
    categories: [IconCategory.DOCUMENT, IconCategory.SYSTEM],
    tags: ["garbage", "delete", "destroy", "recycle", "recycling"],
    Icon: Icon.Trash,
  },
  {
    name: "trash-handle",
    categories: [IconCategory.DOCUMENT, IconCategory.SYSTEM],
    tags: ["garbage", "delete", "destroy", "recycle", "recycling"],
    Icon: Icon.TrashHandle,
  },
  {
    name: "triangle",
    categories: [IconCategory.OTHER],
    tags: ["3", "shapes", "polygons"],
    Icon: Icon.Triangle,
  },
  {
    name: "triangle-down",
    categories: [IconCategory.OTHER],
    tags: ["3", "shapes", "polygons"],
    Icon: Icon.TriangleDown,
  },
  {
    name: "triangle-left",
    categories: [IconCategory.OTHER],
    tags: ["3", "shapes", "polygons"],
    Icon: Icon.TriangleLeft,
  },
  {
    name: "triangle-right",
    categories: [IconCategory.OTHER],
    tags: ["3", "shapes", "polygons"],
    Icon: Icon.TriangleRight,
  },
  {
    name: "triangle-up",
    categories: [IconCategory.OTHER],
    tags: ["3", "shapes", "polygons"],
    Icon: Icon.TriangleUp,
  },
  {
    name: "truck",
    categories: [IconCategory.BUSINESS, IconCategory.MAP, IconCategory.OTHER],
    tags: ["trucks", "cars", "vehicles", "maps", "shipping", "delivery"],
    Icon: Icon.Truck,
  },
  {
    name: "user-circle",
    categories: [IconCategory.USERS],
    tags: ["person", "users", "account", "login", "round"],
    Icon: Icon.UserCircle,
  },
  {
    name: "video-camera",
    categories: [IconCategory.DEVICE, IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["videography", "film", "recording"],
    Icon: Icon.VideoCamera,
  },
  {
    name: "warning",
    categories: [IconCategory.SYSTEM],
    tags: ["alert", "danger", "dangerous", "caution"],
    Icon: Icon.Warning,
  },
  {
    name: "warning-circle",
    categories: [IconCategory.SYSTEM],
    tags: ["alert", "danger", "dangerous", "caution", "round"],
    Icon: Icon.WarningCircle,
  },
  {
    name: "warning-octagon",
    categories: [IconCategory.SYSTEM],
    tags: ["alert", "danger", "dangerous", "caution", "8", "eight"],
    Icon: Icon.WarningOctagon,
  },
  {
    name: "wifi-high",
    categories: [IconCategory.SYSTEM],
    tags: ["wireless", "internet", "network", "connection", "connectivity"],
    Icon: Icon.WifiHigh,
  },
  {
    name: "wifi-high-alt",
    categories: [IconCategory.SYSTEM],
    tags: ["wireless", "internet", "network", "connection", "connectivity"],
    Icon: Icon.WifiHighAlt,
  },
  {
    name: "wifi-low",
    categories: [IconCategory.SYSTEM],
    tags: ["wireless", "internet", "network", "connection", "connectivity"],
    Icon: Icon.WifiLow,
  },
  {
    name: "wifi-low-alt",
    categories: [IconCategory.SYSTEM],
    tags: ["wireless", "internet", "network", "connection", "connectivity"],
    Icon: Icon.WifiLowAlt,
  },
  {
    name: "wifi-medium",
    categories: [IconCategory.SYSTEM],
    tags: ["wireless", "internet", "network", "connection", "connectivity"],
    Icon: Icon.WifiMedium,
  },
  {
    name: "wifi-medium-alt",
    categories: [IconCategory.SYSTEM],
    tags: ["wireless", "internet", "network", "connection", "connectivity"],
    Icon: Icon.WifiMediumAlt,
  },
  {
    name: "wifi-none",
    categories: [IconCategory.SYSTEM],
    tags: ["wireless", "internet", "network", "connection", "connectivity"],
    Icon: Icon.WifiNone,
  },
  {
    name: "wifi-none-alt",
    categories: [IconCategory.SYSTEM],
    tags: ["wireless", "internet", "network", "connection", "connectivity"],
    Icon: Icon.WifiNoneAlt,
  },
  {
    name: "x",
    categories: [IconCategory.SYSTEM, IconCategory.OTHER],
    tags: ["closed", "cancelled", "dismissed"],
    Icon: Icon.X,
  },
  {
    name: "x-circle",
    categories: [IconCategory.SYSTEM, IconCategory.OTHER],
    tags: ["closed", "cancelled", "dismissed", "round"],
    Icon: Icon.XCircle,
  },
  {
    name: "x-square",
    categories: [IconCategory.SYSTEM, IconCategory.OTHER],
    tags: ["closed", "cancelled", "dismissed"],
    Icon: Icon.XSquare,
  },
];
