import * as Icon from "phosphor-react";
import { IconEntry, IconCategory } from ".";

export const icons: Readonly<IconEntry[]> = [
  {
    name: "arrow-up-right-circle",
    categories: [IconCategory.DESIGN],
    tags: ["pointer", "direction", "round"],
    Icon: Icon.ArrowUpRightCircle,
  },
  {
    name: "backspace",
    categories: [IconCategory.SYSTEM],
    tags: ["keyboard", "remove", "delete"],
    Icon: Icon.Backspace,
  },
  {
    name: "battery-half",
    categories: [IconCategory.DEVICE, IconCategory.SYSTEM],
    tags: ["charged", "charger", "charging", "power"],
    Icon: Icon.BatteryHalf,
  },
  {
    name: "book-closed",
    categories: [IconCategory.DOCUMENT, IconCategory.OTHER],
    tags: ["reading", "reader", "novel", "story"],
    Icon: Icon.BookClosed,
  },
  {
    name: "calendar-x",
    categories: [IconCategory.BUSINESS, IconCategory.SYSTEM],
    tags: ["dates", "times", "events", "schedule", "closed", "cancelled"],
    Icon: Icon.CalendarX,
  },
  {
    name: "check-circle",
    categories: [IconCategory.BUSINESS, IconCategory.SYSTEM],
    tags: ["todo", "to-do", "list", "checkbox", "round"],
    Icon: Icon.CheckCircle,
  },
  {
    name: "clock",
    categories: [IconCategory.SYSTEM],
    tags: ["times", "timer", "alarm", "schedule", "events", "watch"],
    Icon: Icon.Clock,
  },
  {
    name: "cloud",
    categories: [
      IconCategory.BUSINESS,
      IconCategory.SYSTEM,
      IconCategory.WEATHER,
    ],
    tags: ["serverless", "backup", "storage"],
    Icon: Icon.Cloud,
  },
  {
    name: "copy",
    categories: [IconCategory.EDITOR, IconCategory.SYSTEM],
    tags: ["duplicated", "copied"],
    Icon: Icon.Copy,
  },
  {
    name: "cube",
    categories: [IconCategory.DESIGN, IconCategory.OTHER],
    tags: ["square", "box", "3d", "volume", "blocks"],
    Icon: Icon.Cube,
  },
  {
    name: "document-text",
    categories: [IconCategory.DOCUMENT, IconCategory.EDITOR],
    tags: ["documents", "files", "save", "write"],
    Icon: Icon.DocumentText,
  },
  {
    name: "droid",
    categories: [
      IconCategory.BRAND,
      IconCategory.COMMUNICATION,
      IconCategory.DEVELOPMENT,
      IconCategory.DEVICE,
      IconCategory.SYSTEM,
    ],
    tags: ["android", "google", "mobile", "phone", "cellular", "cellphone"],
    Icon: Icon.Droid,
  },
  {
    name: "envelope",
    categories: [IconCategory.COMMUNICATION],
    tags: ["mail", "email", "send", "sent", "message"],
    Icon: Icon.Envelope,
  },
  {
    name: "envelope-alt",
    categories: [IconCategory.COMMUNICATION],
    tags: ["mail", "email", "send", "sent", "message"],
    Icon: Icon.EnvelopeAlt,
  },
  {
    name: "folder",
    categories: [
      IconCategory.DOCUMENT,
      IconCategory.EDITOR,
      IconCategory.SYSTEM,
    ],
    tags: ["directory", "directories", "files"],
    Icon: Icon.Folder,
  },
  {
    name: "folder-dip",
    categories: [
      IconCategory.DOCUMENT,
      IconCategory.EDITOR,
      IconCategory.SYSTEM,
    ],
    tags: ["directory", "directories", "files"],
    Icon: Icon.FolderDip,
  },
  {
    name: "folder-minimal",
    categories: [
      IconCategory.DOCUMENT,
      IconCategory.EDITOR,
      IconCategory.SYSTEM,
    ],
    tags: ["directory", "directories", "files"],
    Icon: Icon.FolderMinimal,
  },
  {
    name: "heart",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.DESIGN,
      IconCategory.HEALTH,
      IconCategory.OTHER,
    ],
    tags: ["wellness", "love", "healthy", "like"],
    Icon: Icon.Heart,
  },
  {
    name: "horse",
    categories: [IconCategory.HEALTH, IconCategory.OTHER],
    tags: ["animals", "equestrian", "chess", "knight", "games", "sports"],
    Icon: Icon.Horse,
  },
  {
    name: "microphone",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.DEVICE,
      IconCategory.MEDIA,
      IconCategory.SYSTEM,
    ],
    tags: ["microphone", "audio", "recording", "music", "sound", "podcast"],
    Icon: Icon.Microphone,
  },
  {
    name: "minus-circle",
    categories: [
      IconCategory.DEVELOPMENT,
      IconCategory.FINANCE,
      IconCategory.OTHER,
    ],
    tags: [
      "subtraction",
      "difference",
      "mathematics",
      "arithmetic",
      "calculator",
      "round",
    ],
    Icon: Icon.MinusCircle,
  },
  {
    name: "music-notes-sixteenth",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["songs", "audio", "playlist", "albums"],
    Icon: Icon.MusicNotesSixteenth,
  },
  {
    name: "pencil-clip",
    categories: [IconCategory.DESIGN, IconCategory.EDITOR],
    tags: ["write", "writing", "editing", "sign", "signature"],
    Icon: Icon.PencilClip,
  },
  {
    name: "pencil-line",
    categories: [IconCategory.DESIGN, IconCategory.EDITOR],
    tags: ["write", "writing", "editing", "sign", "signature"],
    Icon: Icon.PencilLine,
  },
  {
    name: "pen-nib",
    categories: [IconCategory.DESIGN, IconCategory.EDITOR],
    tags: [
      "write",
      "writing",
      "editing",
      "sign",
      "signature",
      "fountain pen",
      "illustrator",
    ],
    Icon: Icon.PenNib,
  },
  {
    name: "pin",
    categories: [IconCategory.MAP],
    tags: ["places", "markers", "locations"],
    Icon: Icon.Pin,
  },
  {
    name: "play-circle",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["resume", "music", "start", "round"],
    Icon: Icon.PlayCircle,
  },
  {
    name: "plus-circle",
    categories: [
      IconCategory.DEVELOPMENT,
      IconCategory.FINANCE,
      IconCategory.OTHER,
    ],
    tags: [
      "addition",
      "sum",
      "mathematics",
      "arithmetic",
      "calculator",
      "round",
    ],
    Icon: Icon.PlusCircle,
  },
  {
    name: "prohibit",
    categories: [IconCategory.MAP, IconCategory.SYSTEM, IconCategory.OTHER],
    tags: [
      "forbidden",
      "prohibited",
      "cancelled",
      "prevent",
      "stop",
      "do not enter",
    ],
    Icon: Icon.Prohibit,
  },
  {
    name: "search",
    categories: [IconCategory.EDITOR, IconCategory.SYSTEM],
    tags: ["find", "locate", "query"],
    Icon: Icon.Search,
  },
  {
    name: "smiley",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.DESIGN,
      IconCategory.OTHER,
    ],
    tags: ["face", "smiley", "emoji", "unimpressed"],
    Icon: Icon.Smiley,
  },
  {
    name: "smiley-meh",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.DESIGN,
      IconCategory.OTHER,
    ],
    tags: ["face", "smiley", "emoji", "unimpressed"],
    Icon: Icon.SmileyMeh,
  },
  {
    name: "speaker-off",
    categories: [IconCategory.MEDIA, IconCategory.SYSTEM],
    tags: ["muted", "volume", "sound", "music"],
    Icon: Icon.SpeakerOff,
  },
  {
    name: "star",
    categories: [
      IconCategory.COMMUNICATION,
      IconCategory.MAP,
      IconCategory.OTHER,
    ],
    tags: ["rate", "ratings", "favorites"],
    Icon: Icon.Star,
  },
  {
    name: "trash",
    categories: [IconCategory.DOCUMENT, IconCategory.SYSTEM],
    tags: ["garbage", "delete", "destroy", "recycle", "recycling"],
    Icon: Icon.Trash,
  },
  {
    name: "two-circle",
    categories: [IconCategory.DESIGN],
    tags: ["number", "digit", "2", "round"],
    Icon: Icon.TwoCircle,
  },
  {
    name: "user-circle",
    categories: [IconCategory.USERS],
    tags: ["person", "users", "account", "login", "round"],
    Icon: Icon.UserCircle,
  },
  {
    name: "warning-triangle",
    categories: [IconCategory.SYSTEM],
    tags: ["alert", "danger", "dangerous", "caution"],
    Icon: Icon.WarningTriangle,
  },
  {
    name: "wifi-medium",
    categories: [IconCategory.SYSTEM],
    tags: ["wireless", "internet", "network", "connection", "connectivity"],
    Icon: Icon.WifiMedium,
  },
];
